# Generated by Django 3.1.5 on 2021-02-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_s', models.CharField(max_length=10)),
                ('l_s', models.CharField(max_length=10)),
                ('exp_id', models.IntegerField()),
            ],
        ),
    ]
